Makefile: cleanup and fixes
- Fix ROOT file check
- Fix prerequisites
- Fix run all tests target
- Add discover target

diff --git a/veloview/Makefile b/veloview/Makefile
--- a/veloview/Makefile
+++ b/veloview/Makefile
@@ -1,21 +1,41 @@
+## Makefile with targets to run tests.
+#
+# Although sourcing sourceme.sh is required for running interactively
+# or using the package from other scripts (w/o installing), it is not
+# necessary to run tests with this Makefile.
+#
+
 TESTS		:= $(wildcard tests/test_*.py)
+
 DQMTESTS	:= test_avghists test_statcomp
+DQMFILES	:= tests/data/dqm_data.root tests/data/dqm_ref.root
 
-.PHONY:	files tests $(TESTS:tests/%.py=%)
+.PHONY:	files tests discover $(TESTS:tests/%.py=%)
 
-tests:	files $(TESTS)
-	@for t in $^; \
-         do \
-            $$t $(OPTS); \
-         done
+# all tests
+tests:	$(TESTS:tests/%.py=%)
 
-test-dqm:	files
+# tests on dqm files (listed by hand in DQMTESTS)
+test-dqm:	$(DQMTESTS)
 
+# extra requirement for tests with dqm files
+$(DQMTESTS):%:	files
+
+# common rule for all tests
 $(TESTS:tests/%.py=%):%:	tests/%.py
-	$^ $(OPTS)
+	$< $(OPTS)
 
+# same as above, but run under pdb
+$(DQMTESTS:%=debug_%):%:	files
 $(TESTS:tests/%.py=debug_%):debug_%:	tests/%.py
 	python -m pdb $^
 
-files:	$(wildcard tests/data/dqm_*.root)
-	@test -n "$^" || { echo Missing ROOT files && false; }
+# test for dqm files
+files:	
+	@for f in $(DQMFILES); \
+	  do test -f $$f || { echo "Missing ROOT file: $$f" && break; } \
+	done
+
+# discover tests with unittest
+discover:	files
+	python -m unittest discover $(OPTS)
